### ISSUE TITLE
Brainstorm drinking effects

### ISSUE THREAD

**Issue by ClaudiaLapalme** [Aleoris/DRUNK#10]
* How many types of drinks should we have?
* What types of effects should they have?

**Note**: make sure that all of the effects are fairly feasible for a 1-2 month project.

**Comment by EvanDime** [comment]
Not sure if this is the best place to write ideas but here are some i've had:

 name       | effect           | score effect  | duration 
----------|--------------|--------------|----------
 flipped-up turned upside down     | inverse up/down left/right controls| high score increase | 20s |
 misty stepped    | player stops moving but every 2 seconds they teleport in the direction they are looking     |   high score increase | 30s |
clearly there | temporary invisibility, NPC's will go to last known location | decrease score multiplier | 15s
number 2 | player leaves a trail behind them that slows anyone who walks on it | neutral score effect | idk like 20s?

**Comment by ClaudiaLapalme** [comment]
Of the beers that @EvanDime suggested, I like them all (number 2 is disgustingly hilarious), but I'm not sure how difficult it would be to implement the number 2. The others should be pretty do-able.

I think that about 5-6 beers should be enough for this game, so here are my recommendations:

| name | effect | score effect | duration |
| -----  | -----  | -----------  | --------  |
| Blue Buffalo | player runs at a faster speed | negative score effect  | 15-20s  |
| Pink eye  | camera blacks out for a half second every other second since the player is scratching their eyes | increase multiplier  | 20s  |
| beer  | gradually worsens camera view | increases score multiplier  | stacks on top of other beers throughout the game  |
| derby girl  | The player is now on roller skates! Increase the slipperiness of the ground | multiplier increase  | 20s  |
| water  | sobers up the player a little bit | high score multiplier decreases  | stacks on top throughout the game  |

**Comment by ClaudiaLapalme** [comment]
**MVP**

1. Flipped-up turned upside down
2. Clearly there
3. Blue Buffalo
