### ISSUE TITLE
NPC Spawning Mechanism

### ISSUE THREAD

**Issue by Aleoris** [Aleoris/DRUNK#31]
* Spawn a fixed number of NPCs on the map at the beginning of the game according to the difficulty selected by the player
* Spawn a random number of NPCs every time the player drinks. The range should change according to the difficulty selected by player

**Comment by tedgag** [comment]
* Spawn the NPCs in a random location within one of the tile prefabs
* Make sure that the NPCs does not collide with anything in the tile, else choose another random spawn location
* Allow being able to spawn multiple NPCs at a time
* Allow setting steering behavior of NPCs on spawn (Wander/Arrive/Idle)
